### DISCUSSION TITLE
Is it possible to drag and drop directly on UploadButton

### DISCUSSION THREAD

**Discussion by jacob-minca** [rpldy/react-uploady#530] [Q&A] [answered]
I wanted to see if it was possible to allow dragging and dropping on the `UploadButton`. To my understanding, I thought you would be able since the `UploadButton` is inside the `UploadDropZone`. Every time I drag a file over the `UploadButton`, the file gets opened in my browser. It seems like the `UploadButton` isn't considered the drop zone.

```
return (
<UploadDropZone
    className={`p-4 sm:p-24 w-full ${uploading ? "hidden" : ""}`}
    onDragOverClassName="bg-gray-200"
>
    <UploadButton
        text={uploading ? "Uploading..." : buttonText}
    />
</UploadDropZone>)
```

**Comment by yoavniran** [comment]
hey @jacob-minca 
Without resorting to complicated and probably buggy javascript. I'd solve this using CSS.
Specifically, hide the button when the drag is over the drop-zone.

simple example with styled-components:

```jsx

const StyledDropZoneWithButton = styled(UploadDropZone)`
  &.drag-over {
      button {
          display: none;
      }
  }
`;

const WithUploadButtonInside = () => {
    return (
        <Uploady>
            <StyledDropZoneWithButton
                onDragOverClassName="drag-over"
            >
                <UploadButton />
            </StyledDropZoneWithButton>
        </Uploady>
     );
}

```

**Comment by MikeiLL** [comment, marked as answer]
Hey, @yoavniran. 

Amazing work. Thank you.

Hope I'm not incurring on your SciFi writing here with my spam.

Ultimate, I would love to have a DropZone which supports Drag _or_ Click, like in [React DropZone](https://react-dropzone.js.org/#section-basic-example).

Current approach, following your suggestion here, is to include a `<UploadButton>` _and_ a `<span>`, toggling between them on `dropzone.drag-over`:

```js
<Uploady
    destination={{ url: upload_url + "&doctype=" + selectedDocType }}
>
    <UploadDropZone
        className="dropzone"
        onDragOverClassName="drag-over"
    >
        <UploadButton>Drag files or click here to upload.</UploadButton>
        <span>Drag files or click here to upload.</span>
    </UploadDropZone>
</Uploady>
```

```css
.dropzone {
    align-items: center;
    padding: 20px;
    border-width: 2px;
    border-radius: 6px;
    margin: 0 2em;
    border-color: #898989;
    border-style: dashed;
    background-color: #fafafa;
    color: #898989;
    outline: none;
    transition: border .24s ease-in-out;
}

.dropzone button {
    border: none;
    background: none;
    color: inherit;
    font-size: inherit;
    font-family: inherit;
    font-weight: inherit;
    line-height: inherit;
    letter-spacing: inherit;
}

.dropzone.drag-over button {
    display: none;
}

.dropzone:not(.drag-over) span {
    display: none;
}
```

Would this be the approach you'd recommend?
